# Generated by Django 3.2.8 on 2021-12-17 07:47

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='عبارت لینک')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='موضوع مقاله')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='عبارت لینک')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='مقاله')),
                ('status', models.CharField(choices=[('draft', 'پیش نویس'), ('publish', 'در حال انتشار')], default='publish', max_length=100, verbose_name='وضعیت')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('tag', models.ManyToManyField(related_name='articles', to='blog.Tag', verbose_name='برچسب')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ('-timestamp',),
            },
        ),
    ]
